[project]
name = "sanic-api"
version = "0.1.0"
description = ""
authors = [
    { name = "昊色居士", email = "xhrtxh@gmail.com" },
]
dependencies = [
    "sanic>=22.9.1",
    "pydantic>=1.10.2",
    "sanic-ext>=22.9.1",
    "loguru>=0.6.0",
    "orjson>=3.8.2",
    "pygments>=2.13.0",
]
requires-python = ">=3.8"
readme = "README.MD"
license = { text = "MIT" }
[project.optional-dependencies]


[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]

[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
verify_ssl = true

[tool.black]
line-length = 110
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 110
include_trailing_comma = true

[tool.pdm.dev-dependencies]
dev = [
    # 代码格式化
    "black>=22.10.0",
    # 导入格式化
    "isort>=5.10.1",
]